# Generated by Django 5.2 on 2025-05-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('result', models.CharField(blank=True, choices=[('1-0', 'White wins'), ('0-1', 'Black wins'), ('1/2-1/2', 'Draw')], max_length=7, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('ply1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_games', to='players.player')),
                ('ply2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_games', to='players.player')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaderboard.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveIntegerField(default=0)),
                ('dislike', models.PositiveIntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='featured_games.game')),
            ],
        ),
    ]
