# Generated by Django 5.2 on 2025-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
