# Generated by Django 5.2 on 2025-04-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_games', '0002_game_round'),
        ('leaderboard', '0003_remove_tournament_games_tournament_currently_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(default='true', on_delete=django.db.models.deletion.CASCADE, to='leaderboard.tournament'),
            preserve_default=False,
        ),
    ]
