# Generated by Django 5.2 on 2025-04-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured_games', '0003_game_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
    ]
