# Generated by Django 5.2 on 2025-04-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_games', '0005_game_tournament'),
        ('leaderboard', '0003_remove_tournament_games_tournament_currently_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaderboard.tournament'),
        ),
    ]
