# Generated by Django 5.2 on 2025-05-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_games', '0008_alter_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
