# Generated by Django 5.2 on 2025-04-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('featured_games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('butch', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('games', models.ManyToManyField(to='featured_games.game')),
                ('winner1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place', to='players.player')),
                ('winner2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place', to='players.player')),
                ('winner3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place', to='players.player')),
            ],
        ),
    ]
