# Generated by Django 5.2 on 2025-05-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currently_active', models.BooleanField(default=True)),
                ('winner1', models.ManyToManyField(blank=True, related_name='first_place', to='players.player')),
                ('winner2', models.ManyToManyField(blank=True, related_name='second_place', to='players.player')),
                ('winner3', models.ManyToManyField(blank=True, related_name='third_place', to='players.player')),
            ],
        ),
    ]
