# Generated by Django 5.2 on 2025-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_delete_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
        migrations.AddField(
            model_name='tournament',
            name='currently_active',
            field=models.BooleanField(default=True),
        ),
    ]
