# Generated by Django 5.2 on 2025-04-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_tournament_games_tournament_currently_active'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winner1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place', to='players.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place', to='players.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place', to='players.player'),
        ),
    ]
