import { Player,FeaturedGame } from "./types"

// Mock data for featured games
export const featuredGamesData: FeaturedGame[] = [
  {
    id: 1,
    white: "Magnus Carlsen",
    black: "Fabiano Caruana",
    event: "World Championship 2018",
    date: "2018-11-28",
    result: "1-0",
    moves: 55,
    opening: "Sicilian Defense",
    description: "A brilliant attacking game where Carlsen sacrificed material for a devastating kingside attack.",
    likes: 245,
    dislikes: 12,
    views: 12500,
    duration: "4h 12m",
    image: "/placeholder.svg?height=200&width=350",
    userLiked: false,
    userDisliked: false,
  },
  {
    id: 2,
    white: "Hikaru Nakamura",
    black: "Wesley So",
    event: "US Championship 2021",
    date: "2021-10-15",
    result: "½-½",
    moves: 67,
    opening: "Queen's Gambit Declined",
    description: "An incredible defensive masterpiece by So, saving a seemingly lost position against Nakamura.",
    likes: 189,
    dislikes: 8,
    views: 8700,
    duration: "3h 45m",
    image: "/placeholder.svg?height=200&width=350",
    userLiked: false,
    userDisliked: false,
  },
  {
    id: 3,
    white: "Ding Liren",
    black: "Ian Nepomniachtchi",
    event: "World Championship 2023",
    date: "2023-04-30",
    result: "1-0",
    moves: 68,
    opening: "Nimzo-Indian Defense",
    description: "The decisive game of the 2023 World Championship match, featuring a brilliant queen sacrifice.",
    likes: 312,
    dislikes: 15,
    views: 18200,
    duration: "5h 03m",
    image: "/placeholder.svg?height=200&width=350",
    userLiked: false,
    userDisliked: false,
  },
  {
    id: 4,
    white: "Garry Kasparov",
    black: "Veselin Topalov",
    event: "Wijk aan Zee 1999",
    date: "1999-01-20",
    result: "1-0",
    moves: 44,
    opening: "Pirc Defense",
    description: "Kasparov's famous 'Immortal Game' featuring one of the greatest combinations in chess history.",
    likes: 523,
    dislikes: 5,
    views: 45800,
    duration: "3h 22m",
    image: "/placeholder.svg?height=200&width=350",
    userLiked: false,
    userDisliked: false,
  },
  {
    id: 5,
    white: "Bobby Fischer",
    black: "Boris Spassky",
    event: "World Championship 1972",
    date: "1972-07-23",
    result: "1-0",
    moves: 41,
    opening: "Sicilian Defense",
    description: "Game 6 of the 'Match of the Century', showcasing Fischer's brilliant positional play.",
    likes: 478,
    dislikes: 7,
    views: 38900,
    duration: "2h 55m",
    image: "/placeholder.svg?height=200&width=350",
    userLiked: false,
    userDisliked: false,
  },
]
